config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  resources :developers, only: [:index, :show]

  root to: "home#index"

  resources :about, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games
  validates :name, presence: true, uniqueness: true

  paginates_per 8

  def games_list
    games.map { |game| game.name }.join
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :developer

  has_many :game_genres, -> {includes :genres}
  has_many :genres, through: :game_genres

  has_many :game_platforms
  has_many :platforms, through: :game_platforms

  def init
    self.developer_id ||= 0 if self.developer.has_attribute? :developer_id
  end

  validates :name, presence: true
  validates :rating, :total_rating, numericality: true

  paginates_per 5

  def genres_list
    genres.map { |genre| genre.name }.join
  end

  def platforms_list
    platforms.map { |platform| platform.name }.join
  end
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :game_genres
  has_many :genres, through: :game_genres

  validates :name, presence: true, uniqueness: true
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :game_platforms
  has_many :platforms, through: :game_platforms

  validates :name, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    @developers = Developer.all.page(params[:page])
  end

  def show
    @developer = Developer.find(params[:id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.includes(:developer).order("name ASC").page(params[:page])
    @search_genres = Genre.pluck(:name).uniq
  end

  def show
    @game = Game.find(params[:id])
  end

  def search
    @search_genres = Genre.pluck(:name).uniq
    wildcard_search = "%#{params[:keywords]}%"
    genre = "%#{params[:category]}%"
    @games = Game.where("name LIKE ?", wildcard_search).order("name ASC")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<% content_for(:html_title) { "About" } %>

</br>
<h1>About</h1>

  <div class="row">
    <div class="col-7">
      <%= image_tag("ERD.png", :alt => "ERD", :style => "width:100%;max-width:600px;") %>
    </div>
    <div class="col-5">
  </br>
    <p>For the Rails Intro Project, I plan to use the IGDB API, and will pull information from four separate URLs:</p>
    <ol>
      <li><a href="https://api.igdb.com/v4/games/">https://api.igdb.com/v4/games/</a></li>
      <li><a href="https://api.igdb.com/v4/companies/">https://api.igdb.com/v4/companies/</a></li>
      <li><a href="https://api.igdb.com/v4/platforms/">https://api.igdb.com/v4/platforms/</a></li>
      <li><a href="https://api.igdb.com/v4/genres/">https://api.igdb.com/v4/genres/</a></li>
    </ol>
    <p>Provided in the database schema below are five tables that will be used in the development of the website.</p>
    <p>The <em>developers</em> table will consist of the names of all developers which is found in the companies URL;</p>
    <p>The <em>genres</em> table will store the genre names which is found in the genres URL;</p>
    <p>The <em>games</em> table will contain the name, release date, description, rating, and total ratings (amount of people who rated) which is found in the games URL, in addition to the foreign keys of the <em>developers</em> table and <em>platforms</em> table;</p>
    <p>The <em>platforms</em> table will consist of the names of each console/platform which can be found in the platforms URL;</p>
    <p>The <em>gamegenres</em> and <em>gameplatforms</em> tables will have a many-to-many relationship the <em>games</em> table and either the <em>genres</em> or <em>platforms</em> table.</p>
    </div>
  </div>
</div>

<div>
  </br>

  </br></br>
</div>

app/views/developers/index.html.erb
<% content_for(:html_title) { "Developers" } %>

</br>

<h1>Developers</h1>
<div class="container">

  </br>
  <div class="row">
    <div class="col">
      <h5>Name</h5>
    </div>
  </div>
  <% @developers.each do |developer| %>

  <div class="col">
    <%= link_to developer.name, developer, class: "list-group-item list-group-item-action"  %>
  </div>

  </br>
  <% end %>

  <div class="container pagination justify-content-center" >
    <%= paginate @developers, theme: 'twitter-bootstrap-4', pagination_class: "pagination-md" %>
  </div>

</div>

app/views/developers/show.html.erb
</br>

<% content_for(:html_title) { @developer.name } %>

<div class="text-decoration-none">
  <a href='#' style="text-decoration:none;" onclick='history.go(-1);return false;'>Return</a>
</div>

</br>

<div class="container">
  <h1><%= @developer.name %></h1>

  <p>This developer made <%= pluralize @developer.games.count, "game" %>.</p>
  <div class="container">
    <h4>Games</h4>
    <ul>
      <% @developer.games.each do |game| %>
        <li><%= link_to game.name, game %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/games/index.html.erb
<% content_for(:html_title) { "Games" } %>

</br>

<h1>Games</h1>

<div class="container">

  </br>

  <div class="row">
    <div class="col-3">
      <h5>Name</h5>
    </div>
    <div class="col">
      <h5>Developer</h5>
    </div>
    <div class="col">
      <h5>Release Date</h5>
    </div>
    <div class="col">
      <h5>Rating</h5>
    </div>
  </div>

  <% @games.each do |game| %>
    <div class="row ml">
      <div class="col-3">
        <%= link_to game.name, game %>
      </div>
      <div class="col">
        <%= game.developer.name %>
      </div>
      <div class="col">
        <%= DateTime.strptime(game.release_date.to_s,'%s').strftime("%d/%m/%y") if game.release_date != nil %>
      </div>
      <div class="col">
        <%= game.rating %> from <%= game.total_rating %> individuals
      </div>
    </div>
    </br>
  <% end %>

  <div class="container pagination justify-content-center">
    <%= paginate @games, theme: 'twitter-bootstrap-4', pagination_class: "pagination-md" %>
  </div>

</div>

app/views/games/search.html.erb
<% content_for(:html_title) { "Search: " + params[:keywords] } %>

<p class="mb-5">Search results found <%= pluralize(@games.count, 'video game') %> when searching for: <%= params[:keywords] %></p>

<ul>
  <% @games.each do |game| %>
    <li><%= link_to game.name, game %></li>
  <% end %>
</ul>

app/views/games/show.html.erb
</br>

<% content_for(:html_title) { @game.name } %>

<div class="text-decoration-none">
  <a href='#' style="text-decoration:none;" onclick='history.go(-1);return false;'>Return</a>
</div>

</br>

<div class="container">
  <h1><%= @game.name %></h1>

  <div class="container">

    <p>
      <strong>Genres: </strong>
      <%= @game.genres_list %>
    </p>
    <p>
      <strong>Platform: </strong>
      <%= @game.platforms_list %>
    </p>

    <p>
      <strong>Developer: </strong>
      <%= link_to @game.developer.name, @game.developer %>
    </p>

    <p>
      <div>
        <h5 style="font-weight: bold;">Description:</h5>
        <%= @game.description %>
      </div>
    </p>

  </div>
</div>

app/views/home/index.html.erb
<% content_for(:html_title) { "Home" } %>

</br>

<h1 style="position:absolute;top:45%;left:50%;margin-right:-50%;transform:translate(-50%, -50%);font-size:128px;">Video Game Project!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:html_title) + " - " if content_for?(:html_title) %>Video Game Project!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="display:flex;flex-direction:column;min-height: 100vh;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link" href="/games">Games</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/developers">Developers</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/about">About</a>
          </li>
        </ul>

        <%= form_with(url: search_games_path, method: :get, local: true, class: "form-inline my-2 my-lg-0") do |f| %>
          <div>
            <div>
              <%= text_field_tag(:keywords, nil, class: "form-control ", placeholder: "Video Game Search...") %>
              <%= submit_tag("Search", class: "btn btn-outline-success ") %>
            </div>
          </div>
        <% end %>

      </div>
    </nav>

    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>

    <footer class="page-footer font-small blue pt-4 bg-light" style="flex: 0 0 50px;margin-top:auto;">
      <div class="container">
        <div class="row">

          <div class="col" style="margin-top:10px;">
            <h5>Site Map</h5>
          </div>

          <div class="col">
              <h6><a href="/games" class="list-group-item list-group-item-action">Games</a></h6>
          </div>

          <div class="col">
            <h6><a href="/developers" class="list-group-item list-group-item-action">Developers</a></h6>
          </div>

          <div class="col">
            <h6><a href="/about" class="list-group-item list-group-item-action">About Page</a></h6>
          </div>

        </div>
      </div>
      </br>
    </footer>

  </body>
</html>